trigger:
  branches:
    include:
      - main

pool:
  name: default

steps:
- task: CMake@1
  displayName: "Configurate"
  inputs:
    workingDirectory: 
    cmakeArgs: '--preset=release-Windows'
- task: CMake@1
  displayName: "Build"
  inputs: 
    workingDirectory: 
    cmakeArgs: "--build --preset=release-Windows"
- task: PowerShell@2
  displayName: "Tests"
  inputs:
    targetType: 'inline'
    script: |
        ctest --preset=release-Windows
    failOnStderr: true
    workingDirectory:
- task: PowerShell@2
  displayName: "Benchmarks"
  inputs:
    targetType: 'inline'
    script: |
        .\build\release\WorkFolder\Release\Benchmarks.exe
    workingDirectory:
- task: ArchiveFiles@2
  displayName: "Create archive"
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/build/release/WorkFolder'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/release-artifact.zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: "Publich artifacts"
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'release'
    publishLocation: 'Container'